const app=document.getElementById("app"),KEY="yuga26208_v3";
const D={name:"Explorer",xp:0,played:0,correct:0,badges:[],scores:[]};let s=load(),g,q=[],i=0,xp=0,locked=false;
function load(){try{return {...D,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return {...D}}}
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function shuffle(a){a=[...a];for(let n=a.length-1;n>0;n--){const j=Math.floor(Math.random()*(n+1));[a[n],a[j]]=[a[j],a[n]]}return a}
function accuracy(){return s.played?Math.round(s.correct/s.played*100):0}
function level(){return Math.floor(s.xp/500)+1}
function layout(c){app.innerHTML=`<header><a class="brand" href="#home">YUGA<span>•</span></a><nav><a href="#home">Home</a><a href="#games">Games</a><a href="#culture">Culture</a><a href="#leaderboard">Leaderboard</a><a href="#profile">Profile</a></nav><button class="ghost" onclick="nameEdit()">👤 ${esc(s.name)}</button></header><main>${c}</main><footer>YUGA • SIH PS 26208 • Student Innovation</footer>`}
function nameEdit(){const n=prompt("Player name:",s.name);if(n?.trim()){s.name=n.trim().slice(0,24);save();render()}}
function home(){layout(`<section class="hero"><div><small class="eyebrow">🇮🇳 SIH PS 26208 • TOYS & GAMES</small><h1>Discover India.<br><em>Play its History.</em></h1><p>YUGA transforms Indian civilization, history and culture into interactive learning games.</p><div class="actions"><a class="btn primary" href="#games">Start Exploring →</a><a class="btn secondary" href="#culture">Explore Culture</a></div><div class="stats"><div><b>${s.xp}</b><small>XP</small></div><div><b>${s.played}</b><small>Challenges</small></div><div><b>${accuracy()}%</b><small>Accuracy</small></div></div></div><div class="heroArt"><strong>☼</strong><i>🏛️ Heritage</i><i>📜 History</i><i>🪔 Culture</i></div></section><section class="section"><small class="eyebrow">WHY YUGA</small><h2>Learn through play.</h2><div class="grid four"><article>🎮<h3>Interactive Games</h3><p>Short cultural challenges.</p></article><article>🧠<h3>Learning Moments</h3><p>Facts after every answer.</p></article><article>🏆<h3>Gamified Progress</h3><p>XP, levels and badges.</p></article><article>🌏<h3>Indian Heritage</h3><p>Many eras and traditions.</p></article></div></section>`)}
function games(){layout(`<section class="title"><small class="eyebrow">GAME LIBRARY</small><h1>Choose your challenge</h1><p>Every new game creates a fresh randomized question set.</p></section><div class="grid three">${GAMES.map(g=>`<article class="card"><span class="icon">${g.icon}</span><small>${g.difficulty}</small><h2>${g.title}</h2><p>${g.desc}</p><a class="btn primary" href="#play/${g.id}">Play →</a></article>`).join("")}</div>`)}
function start(id){g=GAMES.find(v=>v.id===id)||GAMES[0];q=shuffle(g.questions).slice(0,5).map(z=>{const opts=shuffle(z.o.map((text,index)=>({text,index})));return {...z,o:opts.map(v=>v.text),a:opts.findIndex(v=>v.index===z.a)}});i=0;xp=0;locked=false;question()}
function question(){const z=q[i];layout(`<section class="game"><div class="gamebar"><a href="#games">← Games</a><b>${g.icon} ${g.title}</b><span>${i+1}/${q.length}</span></div><div class="progress"><i style="width:${i/q.length*100}%"></i></div><article class="question"><small class="eyebrow">RANDOMIZED CHALLENGE ${i+1}</small><h1>${esc(z.q)}</h1><div class="options">${z.o.map((v,n)=>`<button onclick="answer(${n})"><b>${String.fromCharCode(65+n)}</b>${esc(v)}</button>`).join("")}</div><div id="feedback"></div></article><div class="gamebar">⭐ Session XP <b>${xp}</b><span>Level ${level()}</span></div></section>`)}
function answer(n){if(locked)return;locked=true;const z=q[i],ok=n===z.a;document.querySelectorAll(".options button").forEach((b,k)=>{b.disabled=true;if(k===z.a)b.classList.add("correct");if(k===n&&!ok)b.classList.add("wrong")});s.played++;if(ok){s.correct++;xp+=100;s.xp+=100}else xp+=20;if(s.correct>=5&&!s.badges.includes("Heritage Explorer"))s.badges.push("Heritage Explorer");save();document.getElementById("feedback").innerHTML=`<div class="feedback ${ok?"good":"bad"}"><b>${ok?"✓ Correct! +100 XP":"✕ Not quite. +20 XP"}</b><p>${esc(z.fact)}</p><button class="btn primary" onclick="nextQ()">${i===q.length-1?"Finish Game":"Next Challenge →"}</button></div>`}
function nextQ(){i++;if(i<q.length){locked=false;question()}else{ s.scores.push({game:g.title,score:xp,date:new Date().toLocaleDateString()});s.scores=s.scores.slice(-10);save();layout(`<section class="result"><div>🏆</div><small class="eyebrow">JOURNEY COMPLETE</small><h1>Well played, ${esc(s.name)}!</h1><p>Next time you play, the questions and option positions will be randomized again.</p><div class="grid three"><article><b>${xp}</b><small>Game XP</small></article><article><b>${s.correct}</b><small>Total correct</small></article><article><b>${accuracy()}%</b><small>Accuracy</small></article></div><div class="actions center"><a class="btn primary" href="#games">Play Again</a><a class="btn secondary" href="#profile">Profile</a></div></section>`)}}
function culture(){layout(`<section class="title"><small class="eyebrow">CULTURE AT A GLANCE</small><h1>Stories behind the game</h1></section><div class="grid two">${CULTURE.map(c=>`<article class="card"><span class="icon">${c.icon}</span><small>${c.era}</small><h2>${c.title}</h2><b>${c.place}</b><p>${c.text}</p></article>`).join("")}</div>`)}
function leaderboard(){const a=[["Aarav",12450],["Riya",11820],[s.name,s.xp],["Rahul",9870],["Ananya",9420]].sort((a,b)=>b[1]-a[1]);layout(`<section class="title"><small class="eyebrow">COMPETE & LEARN</small><h1>Leaderboard</h1></section><div class="leader">${a.map((v,n)=>`<div><b>#${n+1}</b><span>${n<3?["🥇","🥈","🥉"][n]:"👤"}</span><strong>${esc(v[0])}</strong><b>${v[1].toLocaleString()} XP</b></div>`).join("")}</div>`)}
function profile(){layout(`<section class="profile card"><div class="avatar">👤</div><div><small class="eyebrow">PLAYER PROFILE</small><h1>${esc(s.name)}</h1><p>Level ${level()}</p></div><button class="btn secondary" onclick="nameEdit()">Edit name</button></section><div class="grid four statsCards"><article><b>${s.xp}</b><small>Total XP</small></article><article><b>${s.played}</b><small>Challenges</small></article><article><b>${accuracy()}%</b><small>Accuracy</small></article><article><b>${s.badges.length}</b><small>Badges</small></article></div><section class="section"><h2>Achievements</h2><div class="grid four">${["🏺 Heritage Explorer","🏛️ Monument Master","📜 History Scholar","🗺️ Bharat Navigator"].map(v=>`<article class="badge">${v}</article>`).join("")}</div></section>`)}
function render(){const p=location.hash.slice(1)||"home";if(p.startsWith("play/"))start(p.slice(5));else if(p==="home")home();else if(p==="games")games();else if(p==="culture")culture();else if(p==="leaderboard")leaderboard();else if(p==="profile")profile();else home()}
addEventListener("hashchange",render);render();